spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true   #  to convert service name from upper to lower case in URL eg ACCOUNT to account
      httpclient:
        connect-timeout: 1000    # for timeout if service not respond
        response-timeout: 10s
  data:
    redis:     #start redis from docker
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:    # if want this propertiy for certain endpoint then give name accountsCircuitBreaker as defined in main class
      slidingWindowSize: 10  # min number of request to change status from close
      permittedNumberOfCallsInHalfOpenState: 2   # allow 2 request to decide whether to go open or close
      failureRateThreshold: 50   #  if 50% of request failed move to open state
      waitDurationInOpenState: 10000  # wait 10 sec to move to half open  

