server:
  port: 8080
spring:
  application:
    name: "accounts"       #same as what is defined in config server yaml file name should match
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:mysql://localhost:3307/accountsdb
    driverClassName: org.h2.Driver  # remove for mysql
    username: sa    #root
    password: ''    #root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always     # always execute script mention in schema.sql
  config:
    import: "optional:configserver:http://localhost:8071/"   # optional if u want your service to go up without config server
#      - "application_qa.yml"   //for local yaml configuration
#      - "application_prod.yml"
  profiles:
    active: "prod"     #can have qa and default also
#      - "default"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"       # if only want refresh property then give "refresh" to change property at runtime without restarting service
  info:
    env:
      enabled: true  #for eureka registration
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true  # to shutdown application gracefully
    health:
      probes:
        enabled: true
endpoints:
  shutdown:
    enabled: true
logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG        #package name
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"
                
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      
resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:   # dont do retry if this exception occur
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
