spring:
  application:
    name: "configserver"
  profiles:
#     active: native  #//when using configuration in class paths
    active: git
  cloud:
    config:
      server:
#         native:
#           search-locations: "classpath:/config"
#           search-locations: "file:///E://configFile"
        git:
#          uri: "https://github.com/eazybytes/eazybytes-config.git"
          uri: "https://github.com/aditya951/adityaConfig.git"
          default-label: main  # branch name
          timeout: 5             # wait for 5 sec and through exception if not able to connect
          clone-on-start: true    # clone git repo on startup itself in local system
          force-pull: true        # override all local changes and pull from github
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
        

encrypt:  # to encrypt some value while saving it in github config file see github code 
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
# email: "{cipher}58b34956ac623d4e88fb109d44f6eefd4df15ae5f5b3df009279d5dd76c8c2163be757710ca6c727b8391685c012ff69"   // like this it will
#automatically decrypt and show in service  see postman to decrypt

#curl --location 'http://localhost:8071/encrypt' \
#--header 'Content-Type: text/plain' \
#--data-raw 'aishwarya@eazybank.com'


server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"  